### ISSUE TITLE
Tool does not update pom.xml for dependencies

### ISSUE THREAD

**Issue by mtamboli** [eclipse/transformer#153]
I used the tool to update one of the test application. Everything seems fine but I could not build the application after conversion. Problem was due to not having correct dependency added to the pom.xml. Is it possible for the tool to update pom.xml dependencies as well? That will make the process even smooth.

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /root/apps/transformer/quicksec-jee9/messengerEJB/ejbModule/com/ibm/ws/svt/quicksec/EJB/Messenger.java:[3,19] package jakarta.ejb does not exist
[ERROR] /root/apps/transformer/quicksec-jee9/messengerEJB/ejbModule/com/ibm/ws/svt/quicksec/EJB/Messenger.java:[8,2] cannot find symbol
  symbol: class Remote
[ERROR] /root/apps/transformer/quicksec-jee9/messengerEJB/ejbModule/com/ibm/ws/svt/quicksec/EJB/MessengerBean.java:[2,26] package jakarta.annotation does not exist
```
This problem was resolved by updating pom.xml for all modules:
```
<dependency>  	 
 <groupId>jakarta.platform</groupId>  	 
 <artifactId>jakarta.jakartaee-api</artifactId>  	 
 <version>9.0.0</version>  	 
 <scope>provided</scope>  	
</dependency>
```

**Comment by tbitonti** [comment]
The transformer has no current capability to update POM files.  Such can be added, but will require a new action which is specific to POM files.

To work on this, there will need to be an interested party on-hand to detail the requirements and to validate that the function which is added meets those requirements.

Would updating POM's require updating dependent POM's?

A part of the reason for not already having this function is that processing the POM metadata is more complicated than processing package references.   The transformation of a POM dependency element requires a parse of that element.  At the least, groupId, the artifactId, and the version would need to be determined.
That leads to a potential problem, which is that most java parsers make it hard to preserve the whitespace and comments within the file.  Ideally, the transformation would only minimally update the target resource.

**Comment by bjhargrave** [comment]
Transformer can now update xml and properties files which includes pom.xml and pom.properties. But Transformer does not understand the structure of these files and treats then, line by line, as text files performing text substitutions on each line. Which means the xml transformation cannot properly change the GAV tuple as a unit since they normally occur on different lines in the pom xml file. 

To address the issue you have above, you should use the new `jar` goal of the `transformer-maven-plugin` so that a project transforms a dependency and the project's pom is the pom of the newly transformed artifact. See the following test for an example:

https://github.com/eclipse/transformer/blob/main/maven-plugins/transformer-maven-plugin/src/it/simple-jar/pom.xml

Also see the discussion in https://github.com/eclipse/transformer/issues/139 for some additional information.
