### ISSUE TITLE
Plugin goal to transform dependencies

### ISSUE THREAD

**Issue by OrangeDog** [eclipse/transformer#228]
The current plugin has a single goal - "run" - designed to transform and publish a jakarta variant of the project's target.

What would also be very useful is a goal to transform one or more of the project's dependencies in the pre-compile phase.

**Comment by bjhargrave** [comment]
> What would also be very useful is a goal to transform one or more of the project's dependencies in the pre-compile phase.

Yes. But I am unclear on how that would work in a practical sense.

So your project depends on org:foo:1.1.0 which you need transformed to compile your project. So that could be done, your project compiles, but your resulting artifact's pom shows a dependency on org:foo:1.1.0 which absolutely will not work at runtime.

So I don't think it is enough to just transform, in a transient manner, the dependencies of a project since the project's artifacts need to depend upon a transformed artifact that is persistent.

I think this is a very interesting problem, but I am not sure on how to solve it in a meaningful way. I think you would really need to structure a multi-module project where some projects just transform a dependency of the "main" project into new artifacts with new GAVs and then the "main" project just needs to depends upon the new GAV. Then all the artifacts, transformed dependencies and "main" project, can be released.

But I am very interesting in discussing use cases in this area.

**Comment by OrangeDog** [comment]
Is it not possible to change the resolution of the dependency to a different jar, or add a classifier to the dependency before it's resolved? Things like the shade plugin can change what the runtime dependencies are (in that case, removing them).

**Comment by bjhargrave** [comment]
> Is it not possible to change the resolution of the dependency to a different jar, or add a classifier to the dependency before it's resolved?

If that other jar exists (with the transformed api) with a "transformed" dependency GAV, then why not just compile against it instead of the dependency with the untransformed api?



> Things like the shade plugin can change what the runtime dependencies are (in that case, removing them).

This make sense since shading slurps the other api into the artifact being built while shading it. So you then no longer have an external dependency on the api since you only depend upon the shaded api inside your artifact.

Transforming assume you will depend upon the transformed api that is provided some how. For dependencies which are scope=provided, then it does not matter that your artifact still has a scope=provided dependency since the "container" running your app will provide the transformed api. This is the basic situation with Jakarta EE. But there are Jakarta EE api jars now you can compile against. So I am not sure how many real scope=provided dependencies there are which could be transformed on-the-fly such that the resulting artifact is useful.

This is why I think we need to make some more detailed use cases and have them be as real (concrete) as possible so that we can fully understand what is useful for tooling to do.

**Comment by OrangeDog** [comment]
> If that other jar exists

The point is that it doesn't, and this plugin should create it.

The use case is that you have a dependency that uses the old API, and no version exists that uses the new API, and you want to still be able to use it.

**Comment by bjhargrave** [comment]
The updated maven plugin will include a new `jar` goal which can be used to transform artifacts from a repository. Multiple executions of the `jar` goal can be used to transform multiple artifacts.

**Comment by OrangeDog** [comment]
I am revisiting this and it does not seem that the `jar` goal meets the use case. The transformed jar is not added to the classpath, and the project is still compiled with the original dependency.

**Comment by bjhargrave** [comment]
The transformed jar is not automatically added to the classpath. It can be referenced from another maven project (not the same project) using the maven coordinates of the transformed jar.

**Comment by OrangeDog** [comment]
Right, but that's not what the feature request was.
I do not want to publish transformed jars. I want to use dependencies that will only work if they are transformed first.

The current jar goal also will not work, as the dependencies aren't rewritten. You can hack it with the `maven-shade-plugin`, as long as it resolves all the duplicate files in favour of the transformed version.

**Comment by bjhargrave** [comment]
You do not need to publish the transformed jars. The point of the task is to make a new jar which is a transformation of the original. This new jar has distinct maven coordinates which are different than the original. You cannot overwrite the original jar as the maven coordinates of the original jar mean something different than the transformed jar. They are distinct jars and must have distinct maven coordinates.

**Comment by OrangeDog** [comment]
No, you but you can adjust the dependencies to point at the new jar.
