### ISSUE TITLE
web.xml web-app version is not transformed

### ISSUE THREAD

**Issue by SoftlySplinter** [eclipse/transformer#284]
With the current code on the main branch, I am not seeing the version of the web-app in the web.xml file being transformed. This leads to application errors when it is deployed into a server runtime.

Input `web.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://xmlns.jcp.org/xml/ns/javaee" 
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd"
         id="WebApp_ID"  
         version="4.0">
  <display-name>eclipse-transformer-test</display-name>
</web-app>
```

Transformed `web.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://jakarta.ee/xml/ns/jakartaee" 
         xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-app_4_0.xsd"
         id="WebApp_ID"
         version="4.0">
  <display-name>eclipse-transformer-test</display-name>
</web-app>
```

The schema has been transformed to `https://jakarta.ee/xml/ns/jakartaee`, but is still targeting the web-app 4.0 schema. And the web-app version attribute is still at 4.0. I believe both of these should be 5.0 instead.

This means that the output WAR still needs some updateds to use it on a Jakarta EE 9 runtime.

**Comment by bjhargrave** [comment]
Substitution of text in XML files is done without any XML knowledge. So it does not know that this XML file has semantics and that changing `http://xmlns.jcp.org/xml/ns/javaee=https://jakarta.ee/xml/ns/jakartaee` also means a `version` attribute needs changing. Since changing `version="4.0"` to `version="5.0"` should not be done in all text files (and there is also the case of  `version='4.0'` to `version="5.0"`), you would need to configure a text substitution for `version="4.0"` to `version="5.0"` which targets the xml files which need it.

**Comment by bjhargrave** [comment]
We could add a rule to the Jakarta defaults for `web.xml` only which transforms `version="4.0"` if this would be the only occurrence of `version="4.0"` in a web.xml file.
