### ISSUE TITLE
Transformer not moving individual classes when modifying bytecode

### ISSUE THREAD

**Issue by aberman** [eclipse/transformer#399]
I am using the Transformer to convert Jackson 1 to 2, however, some classes have been moved to completely different packages which don't align with the rename of the entire package.  

For example: 

With a rename rule of: `org.codehaus.jackson.*=com.fasterxml.jackson.core`:

`org.codehaus.jackson.type.JavType` gets renamed to `com.fasterxml.jackson.core.type.JavaType`, which is incorrect, it needs to be `com.fasterxml.jackson.databind.JavaType`.  However, other classes in that `type` subpackage were moved properly according to the rule, so `JavaType` is an exception to the rename rule.  However, when I add that class to the rename rules like so:

`org.codehaus.jackson.type.JavaType=com.fasterxml.jackson.databind.JavaType`

the Transformer fails to move the specific class.  I am running the CLI on a JAR file, so it is not working when modifying bytecode.

Actual result:  `com.fasterxml.jackson.core.type.JavaType`
Expected result: `com.fasterxml.jackson.databind.JavaType`
Version: 0.5.0

**Comment by bjhargrave** [comment]
Transformer handles package renaming not class renaming. It does not have support for moving individual classes from one package to another.

So a package rename rule like 

    org.codehaus.jackson.type.JavaType=com.fasterxml.jackson.databind.JavaType

treats each side as a package name. And, of course, Transformer does not see any classes in the `org.codehaus.jackson.type.JavaType` package because it is not a package.

It sounds like Jackson did both a package renaming and a refactoring at the same time (which is not unreasonable), but Transformer does not currently have any way to support the refactoring. This could be added but it would require a new rule type to be added along with necessary changes in the code base to handle the new rule type.

**Comment by aberman** [comment]
Got ya.  When I run the rule on source code, it does work by renaming the import, so I thought it would work on bytecode.  

Would be great to have a new rule for type renames which overrides the package renames, I imagine this is not an uncommon use case. Thanks @bjhargrave
