### ISSUE TITLE
Manifest Class-Path header not transformed

### ISSUE THREAD

**Issue by riswarichu** [eclipse/transformer#573]
With jakartaDefaults rules set to true the manifest of the jar is not changed. It still have references to javax

**Comment by bjhargrave** [comment]
We are going to need a lot more details on the problem here to better understand the situation. Can you please provide a reproduction of the problem?

**Comment by riswarichu** [comment]
When I create a jar, manifest is created as below

Manifest-Version: 1.0
Build-Jdk-Spec: 11
**Class-Path: javax.transaction-api.jar**
Implementation-Title: richu
Implementation-Version: 0.0.1-SNAPSHOT
Created-By: TEST - Apache Maven 3.6.3
Multi-Release: true

With the transformer, the javax reference in Cass-path of Manifest file is not changed, though the javax reference available inside the source class files are changed

**Comment by bjhargrave** [comment]
Thanks for the explanation. Transformer does not do anything with the Class-Path manifest header since it references things outside of the jar. The ManifestActionImpl only processes select manifest headers for package name changes.

https://github.com/eclipse/transformer/blob/7b215ab3676a19ed4dcb1ce9a2f556f90a476b73/org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ManifestActionImpl.java#L141-L142

So for this case, you will need to modify the Class-Path manifest entry in some other way.
